#!/usr/bin/python3
# download-file
# Client-side command
"""
download-file description.
"""
from lib.cli_parse import parse_args_download
from lib.socket_tcp import Socket
from lib.protocol import (
    send_opcode, DOWNLOAD_FILE_OP, send_filename, recv_file)
from lib.logger import logger


def main():
    """
    TODO: Description
    """

    args = parse_args_download()

    skt = Socket()
    skt.connect(args.ADDR, args.PORT)

    send_opcode(skt, DOWNLOAD_FILE_OP)
    send_filename(skt, args.FILENAME)

    with open(args.FILEPATH, 'wb') as f:
        for file_chunk in recv_file(skt):
            f.write(file_chunk)

    return


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        logger.fatal(e)
