#!/usr/bin/python3
"""
Sends a request to the specified server in order to download the specified
file.
"""

from lib.cli_parse import parse_args_download
from lib.socket_tcp import Socket
from lib.logger import logger
import lib.protocol as prt


def main(args):
    logger.setLevel(args.level)

    skt = Socket()
    skt.connect(args.ADDR, args.PORT)

    prt.send_opcode(skt, prt.DOWNLOAD_FILE_OP)
    s = prt.recv_status(skt)
    if s:
        raise RuntimeError(prt.get_error_msg(s))

    prt.send_filename(skt, args.FILENAME)
    s = prt.recv_status(skt)
    if s:
        raise RuntimeError(prt.get_error_msg(s))

    with open(args.FILEPATH, 'wb') as f:
        for file_chunk in prt.recv_file(skt):
            f.write(file_chunk)

    return 0


if __name__ == "__main__":
    args = parse_args_download()
    try:
        main(args)
    except BaseException as e:
        logger.fatal(e)
        exit(1)
