#!/usr/bin/python3
# list-files
# Client-side command
"""
List Files description.
"""
from lib.cli_parse import parse_args_list


def main():
    """
    TODO: Description
    """

    args = parse_args_list()
    (args.host, args.port)  # address

    return


if __name__ == "__main__":
    main()
