#!/usr/bin/python3
# upload-file
# Client-side command
"""
Upload file script description.
"""
from lib.client.parse import parse_args_upload


def main():
    """
    TODO: description
    """

    args = parse_args_upload()
    (args.host, args.port)  # address

    return


if __name__ == "__main__":
    main()
