#!/usr/bin/python3
"""
Upload file script description.
"""
from os import path
from lib.cli_parse import parse_args_upload
from lib.socket_tcp import Socket
from lib.protocol import UPLOAD_FILE_OP, send_opcode, send_file, send_filename
from lib.logger import logger


def main():
    """
    TODO: description
    """

    args = parse_args_upload()

    if not path.isfile(args.FILEPATH):
        raise FileNotFoundError(f"File not found: {args.FILEPATH}")

    skt = Socket()
    skt.connect(args.ADDR, args.PORT)

    send_opcode(skt, UPLOAD_FILE_OP)

    send_filename(skt, args.FILENAME)

    with open(args.FILEPATH, 'rb') as f:
        send_file(skt, f)

    return 0


if __name__ == "__main__":
    try:
        main()
    except BaseException as e:
        logger.fatal(e)
