#!/usr/bin/python3
# upload-file
# Client-side command
"""
Upload file script description.
"""
from lib.cli_parse import parse_args_upload
from lib.socket_tcp import Socket
from os import SEEK_END, SEEK_SET


def main():
    """
    TODO: description
    """

    args = parse_args_upload()

    socket = Socket()
    socket.connect(args.host, args.port)

    socket.send_file(args.name, args.dst)

    return


if __name__ == "__main__":
    main()
